# Generated by Django 4.1.4 on 2022-12-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org_mail',
        ),
        migrations.AddField(
            model_name='user',
            name='org_id',
            field=models.IntegerField(default=0),
        ),
    ]
