# Generated by Django 4.1.4 on 2022-12-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_org_mail_user_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org_id',
        ),
        migrations.AddField(
            model_name='user',
            name='org_mail',
            field=models.CharField(default='abcd', max_length=100, unique=True),
        ),
    ]
