# Generated by Django 4.1.4 on 2022-12-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_org_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org_mail',
        ),
    ]
