# Generated by Django 4.1.4 on 2022-12-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_org_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_mail',
            field=models.CharField(default='Abc', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
    ]
