# Generated by Django 4.1.4 on 2022-12-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_org_mail_alter_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org_mail',
        ),
    ]
