# Generated by Django 4.1.4 on 2022-12-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_org_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
            preserve_default=False,
        ),
    ]
