# Generated by Django 4.1.4 on 2022-12-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'admin'), ('2', 'student'), ('1', 'club_admin')], default='2', max_length=50),
        ),
    ]
