# Generated by Django 4.1.4 on 2022-12-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
