# Generated by Django 3.2.16 on 2022-12-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_is_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ph_num',
            new_name='phone_number',
        ),
    ]
