# Generated by Django 4.1.4 on 2023-01-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_ph_num_user_phone_number'),
        ('user', '0014_user_is_verified'),
    ]

    operations = [
    ]
