# Generated by Django 4.1.4 on 2023-01-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_merge_20230103_0537'),
        ('user', '0015_merge_20230104_1635'),
    ]

    operations = [
    ]
