# Generated by Django 4.1.4 on 2022-12-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_type_event__type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='_type',
            new_name='type',
        ),
    ]
